package hr.dlatecki.algorithms.gen_alg.operators.interfaces;

import java.util.SortedSet;
import hr.dlatecki.algorithms.gen_alg.operators.abstracts.AbstractCrossoverOperator;
import hr.dlatecki.algorithms.gen_alg.population.interfaces.IChromosome;

/**
 * Interface which defines methods for crossover operator. It is recommended that all implementations of crossover
 * operator extend <code>AbstractCrossoverOperator</code> instead of directly implementing this interface.
 * 
 * @author Domagoj Latečki
 * @version 1.0
 * @since 1.8
 * @param <C> Type of chromosome which will be used in the crossover operator.
 * @see IChromosome
 * @see AbstractCrossoverOperator
 */
public interface ICrossoverOperator<C extends IChromosome> {
    
    /**
     * Performs crossover using the given set of chromosomes as parents. The parents are expected to be sorted by their
     * fitness in descending order. All of the parents given in the set will be used in the crossover.
     * 
     * @param parents set which contains chromosomes which will be used in the crossover.
     * @return Chromosome which was generated by the crossover.
     */
    public C doCrossover(SortedSet<C> parents);
}
