// Copyright (C) Domagoj Latečki
// You may use, distribute and modify this code under the terms of the MIT license.
package hr.dlatecki.algorithms.gen_alg.population.interfaces;

import java.util.Collection;
import hr.dlatecki.algorithms.gen_alg.population.abstracts.AbstractPopulationGenerator;

/**
 * Interface which defines methods for population generator. It is recommended that all implementations of population
 * generator extend <code>AbstractPopulationGenerator</code> instead of directly implementing this interface.
 * 
 * @author Domagoj Latečki
 * @version 1.0
 * @since 1.8
 * @param <C> the type of chromosome which will be generated by this population generator.
 * @see IChromosome
 * @see AbstractPopulationGenerator
 */
public interface IPopulationGenerator<C extends IChromosome> {
    
    /**
     * Generates the population of chromosomes of provided size. The specified size must be greater than or equal to 0.
     * 
     * @param size size of population to generate.
     * @return Collection of chromosomes which represents generated population. All chromosomes will have initial
     *         fitness value of 0.
     * @throws IllegalArgumentException thrown if specified size if not greater than or equal to 0.
     */
    public Collection<C> generatePopulation(int size);
}
